### ISSUE TITLE
Error playing on OTT Navigator

### ISSUE THREAD

**Issue by usg-cloud** [lalitjoshi06/Tplay_All#5]
I have deployed to render as well as downloaded the local m3u but it is not working on OTT Navigator or tivimate for the render url or the local m3u.
Device: Bluestacks and NoxPlayer
Ott Navigator version: 1.7.1.4
![image](https://github.com/lalitjoshi06/Tplay_All/assets/172243165/350a6514-93a6-4a7a-945e-2da9996a3d14)

Some help would be appreciated :)

**Comment by lalitjoshi06** [comment]
Everything working fine. you need to check at your end. try to reload data

**Comment by usg-cloud** [comment]
Turns out that Nox Player and Bluestacks does not allow which is why it doesn't work
